# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP33",
  "description": "Датчик в комнате с телевизором"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="sensor"

2
--WebAppBoundary
Content-Disposition: form-data; name="temperature"

21
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="true_teleroom1.png"
Content-Type: image/png

< ./true_teleroom1.png
--WebAppBoundary--

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/detail/
Content-Type: application/json
